version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password   # ✅ Force mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Aditya
      MYSQL_DATABASE: crud_app
      MYSQL_USER: admin                      # ✅ Ajout de l’utilisateur admin
      MYSQL_PASSWORD: Aditya                 # ✅ Mot de passe admin
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - devops-net
    ports:
      - "3306:3306"
    healthcheck:                             # ✅ Vérifie que MySQL est prêt
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build: ./api
    container_name: backend-api
    restart: always
    environment:
      DB_HOST: mysql                         # ✅ Utilise le nom du service
      DB_USER: admin
      DB_PASSWORD: Aditya
      DB_NAME: crud_app
      JWT_SECRET: devopsShackSuperSecretKey
      RESET_ADMIN_PASS: 'true'
    depends_on:
      mysql:
        condition: service_healthy           # ✅ Attends que MySQL soit prêt
    networks:
      - devops-net
    ports:
      - "5000:5000"

  frontend:
    build: ./client1
    container_name: frontend-react
    restart: always
    depends_on:
      - backend
    networks:
      - devops-net
    ports:
      - "3000:3000"

volumes:
  mysql-data:

networks:
  devops-net:                                # ✅ Réseau commun
    driver: bridge
